name: pink_balancer
channels:
    - conda-forge
dependencies:
    - pinocchio >= 2.6.21
    - pip
    - qpsolvers >= 4.2.0
    - pip:
        - gin-config
        - pin-pink
        - posix-ipc
        - upkie
