name: pink_balancer
channels:
    - conda-forge
dependencies:
    - gin-config >= 0.5.0
    - pinocchio >= 3.1.0, <4.0.0
    - meshcat-shapes >= 0.3.0
    - qpmpc >= 3.0.1, <4.0.0
    - qpsolvers >= 4.2.0, <5.0.0
    - pink >= 3.0.0, <4.0.0
    - upkie >= 5.1.0, <6.0.0
