[project]
name = "pinker_balancer"
version = "1.0.0"
description = "The Pinker balancer is a work-in-progress agent for Upkie wheeled bipeds"
requires-python = ">= 3.10"
dependencies = []

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=2,<4"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64"]

[tool.pixi.pypi-dependencies]
pinker = ">=1.0.0,<2"
pinker_balancer = { path = ".", editable = true }

[tool.pixi.dependencies]
c-compiler = "*"  # to compile Pinker's C extension
proxsuite = ">=0.7.2,<0.8"
qpmpc = ">=3.1.0,<4"
qpsolvers = ">=4.3.1,<5"
upkie = ">=13.0.1,<14"

[tool.pixi.feature.viz.dependencies]
rich = "<15"  # viser >=1.0 requires rich <15
trimesh = "*"
viser = ">=1.0.0"

[tool.pixi.feature.viz.tasks]
agent-viz = "python run_agent.py --visualize"

[tool.pixi.environments]
default = { solve-group = "default" }
viz = { features = ["viz"], solve-group = "default" }

[tool.pixi.tasks]
agent = "python run_agent.py"

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = [
    # pyflakes
    "F",
    # pycodestyle
    "E",
    "W",
    # isort
    "I001",
    # pydocstyle
    "D"
]
ignore = [
    "D100",  # we use ## Doxygen comments: https://stackoverflow.com/q/71380065
    "D104",  # we use ## Doxygen comments: https://stackoverflow.com/q/71380065
    "D204",  # ruff does not know we use Doxygen docstrings
    "D205",  # ruff does not know we use Doxygen docstrings
    "D401",  # good for methods but not for class docstrings
    "D405",  # British-style section names are also "proper"!
]

[tool.ruff.lint.per-file-ignores]
"*/tests/*.py" = ["D"]

[tool.ruff.lint.pydocstyle]
convention = "google"
